# Generated by Django 3.1 on 2021-05-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_varations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varations',
            new_name='variations',
        ),
    ]
